version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: airmini_development
    restart: unless-stopped
    environment:
      POSTGRES_USER: airmini_dev
      POSTGRES_PASSWORD: airmini_dev
      POSTGRES_DB: airmini_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
